### ISSUE TITLE
Onboarding Portal - Implementation new layout

### ISSUE THREAD

**Issue by golmek** [golemfactory/onboarding_staging#79]
Implement final designs of Onboarding portal

**Acceptance Criteria:**

```[tasklist]
### Tasks
- [x] add floating logo
- [x] make landing design responsive
- [ ] launch real links on landing page
- [x] use custom font sizes (instead of tailwind defaults)
- [x] launch framer motion
- [x] Tooltips
- [x] accordionds
- [x] usage recommendation cards
- [x] ornaments ( in progress )
- [x] footer
- [x] legal
- [x] custom inputs
- [x] refactor state flow
- [x] separate container/presentation where needed
- [x] create terms and services
- [x] decide scroll behaviour ( in progress )
- [x] remove duplicated icons
- [x] import metamask and trust wallet icons
- [x] cleanup typography
- [x] refactor layout to be reusable
- [x] refactor router
- [x] implement second type of tooltip
- [x] create missing molecules like remondation card wallet state card etc ...
- [x] launch ramp embedded flow
- [x] refactor layout of ramp/swap/transfer
- [x] propose approach to animation
- [x] create history based recommendations
```
```[tasklist]
### Tasks
```

**Comment by golmek** [comment]
Landing in progress. 
We run into issues with mobile

**Comment by golmek** [comment]
Lib for tool-tips - DONE
Implementing Tool tips
